#!/bin/sh -e

if ! kiss list yasm; then (
    cd yasm

    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
) fi

export PATH="$PWD/junk/bin:$PATH"

syslibs="
freetype-harfbuzz
libogg
libvorbis
libpng
libtheora
libvpx
libwebp
pcre2
zlib
zstd
"

conf=""
for lib in $syslibs
do
    # If we have the lib already installed, theres no need to build it again.
    if kiss list "$lib" ; then
        if [ "$lib" = "freetype-harfbuzz" ] ; then
            lib=freetype
        fi
        conf="$conf builtin_$lib=no"
    fi
done

python scons/scripts/scons.py "${MAKEFLAGS:--j$(nproc)}" \
    platform=x11 \
    target=release_debug \
    execinfo=yes \
    pulseaudio=no \
    use_lto=yes \
    production=yes \
    deprecated=no \
    bits=64 \
    $conf

install -Dm755 bin/godot.x11.opt.tools.64 "$1/usr/bin/godot"
