#!/bin/sh -e

# Build autoconf 2.13 for browser's sole use.
(   
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

if ! kiss list yasm; then (
    cd yasm

    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
); fi

for f in zip unzip; do
    if ! kiss list "$f"; then (
        cd "$f"

        make \
            CC="$CC $CFLAGS $CXXFLAGS" \
            -f unix/Makefile generic

        make \
            prefix="$PWD/../junk" \
            -f unix/Makefile install
    ); fi
done

export PATH="$PWD/junk/bin:$PATH"

sed -e 's#%SRCDIR%#'"$(realpath .)"'#g' -e "s#%CFLAGS%#$CFLAGS#g" mozconfig.in > .mozconfig

# Apparently `mach` is now a *bash* script, yet it's marked as /bin/sh.
# So we just update the shebang.
sed -e '1s~/bin/sh~/bin/bash~' mach > _
mv -f _ mach
chmod +x mach

for patch in *.patch; do
    patch -p1 < "$patch"
done

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/browser"

./mach build
./mach stage

mkdir -p "$1/usr/bin"
mkdir -p "$1/usr/lib"

cp -r objdir/dist/palemoon "$1/usr/lib/browser"
ln -s ../lib/browser/palemoon "$1/usr/bin/browser"
