#!/bin/sh -e

# Enable '-no-pie' as it can fix a seg fault in `temacs`.
export CFLAGS="$CFLAGS -no-pie"

./configure \
    --prefix=/usr \
    --with-modules \
    --with-xft \
    --with-x-toolkit=athena \
    --without-toolkit-scroll-bars \
    --without-dbus \
    --without-gconf \
    --without-gsettings \
    --without-rsvg \
    --with-xpm=no \
    --with-tiff=no \
    --with-gnutls=yes

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Better security defaults
(with-eval-after-load 'gnutls
  (setq
   gnutls-verify-error t
   gnutls-min-prime-bits 2048
   gnutls-trustfiles '("/etc/ssl/cert.pem")))

;; Needed unless KISS Linux gains librsvg support
(setq-default shr-blocked-images ".*\.svg$")
EOF

make
make install

rm -rf "$1/usr/lib/systemd"
