#!/bin/sh -e

export DESTDIR="$1"

sed "/add_subdirectory(po)/d" CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build   build
cmake --install build
