#!/bin/sh -e

# Set -Ddefault_library=both by default.
sed "/value: /s/'static'/'both'/" src/script/per_project_options.meson > _
mv -f _ src/script/per_project_options.meson

command -v muon || {
    ./bootstrap.sh build
    export PATH="$PWD/build:$PATH"
}

muon setup \
    -Dprefix=/usr \
    -Dlibcurl=disabled \
    -Ddocs=disabled \
    -Dstatic=true \
    build

ninja -C build
muon -C build install
