#!/bin/sh -e

export DESTDIR="$1"

sed -e 's|.8.4|.8.6|' installer/file84.tcl > installer/file86.tcl
ls installer/file86.tcl
sed -e 's|.8.4|.8.6|' lib/tcl84.tcl > lib/tcl86.tcl
ls lib/tcl86.tcl

# Intended behavior.
# shellcheck disable=2016
echo 'package ifneeded unixfile 1.18.8.6 [list source [file join $dir file86.tcl]]' >> installer/pkgIndex.tcl
sed -e "/interp/s/-exact//;/interp/s/\[info tclversion\]//" installer/zircon.tcl > _
mv -f _ installer/zircon.tcl

tclsh installer/install.tcl \
    -b /usr/bin \
    -l /usr/share/zircon \
    -p "$1" \
    -w /usr/bin/wish \
    -g
