#!/bin/sh -e

export DESTDIR="$1"

# Disale documentation.
sed -e '/^docs:/s/docs-*//' \
    -e '/^install-yes:/s/install-docs//' Makefile.in > _
mv -f _ Makefile.in

./autogen.sh

./configure \
    --prefix=/usr \
    --with-expat \
    --enable-threadsafe-ssl=posix \
    --enable-shared \
    --disable-static

make
make install
