#!/bin/sh -e

export DESTDIR="$1"

# Remove the libstartup-notification.
for p in *.patch; do
  patch -p1 < "$p"
done

meson setup \
    -Dprefix=/usr \
    output

ninja -C output
ninja -C output install
