#!/bin/sh -e

export DESTDIR="$1"


# Remove the libstartup-notification dependency.
patch -p0 < i3-no-libstartup-notification.patch

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
