#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Ddefault_library=both \
    -Dxwayland=enabled \
    -Dexamples=false \
    -Dxcb-errors=disabled \
    -Drenderers=gles2 \
    output

ninja -C output
muon  -C output install
