#!/bin/sh -e

export DESTDIR="$1"


./configure \
    --prefix=/usr \
    --enable-cxx \
    --disable-zstd \
    --disable-webp \
    --without-x

make
make install

# Remove HTML documentation.
rm -rf "$1/usr/share/doc"
