#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --disable-nls \
    --enable-gui=no \
    --enable-static

make
make install
