#!/bin/sh -e

export DESTDIR="$1"

# Remove subprojects folder to avoid cloning them via git.
rm -rf subprojects/

# Disable nls.
sed "/subdir('po')/d" meson.build > _
mv -f _ meson.build

# Enable gobject-introspection if it is installed.
pkg-config --exists gobject-introspection-1.0 && gi=en

# Needed to make the build succeed.
export CFLAGS="$CFLAGS -w"
export CXXFLAGS="$CXXFLAGS -w"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dtests=false \
    -Ddocs=disabled \
    -Dtls_check=false \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    -Dpkcs11_tests=disabled \
    -Dintrospection="${gi:-dis}abled" \
    output

ninja -C output
ninja -C output install
