#!/bin/sh -e

export DESTDIR="$1"

# Check for gettext. Looking to remove completely.
command -v xgettext

# 'Vendor' libtool.
for t in merge update extract perl; do
    ln -sf intltool "intltool-$t"
done
export PATH="$PWD:$PATH"

sed "/DEFAULT_ICON_THEME/s/Symbolic/Color/" app/config/gimpguiconfig.h >_
mv -f _ app/config/gimpguiconfig.h

# If this sed isn't ran, the vector icons will still be built.
sed "/have_vector_icons/s/not//" icons/Symbolic/meson.build > _
mv -f _ icons/Symbolic/meson.build

sed "s/mypaint-brushes-1.0/mypaint-brushes-2.0/" meson.build > _
mv -f _ meson.build

# TODO: remove translations.

meson setup \
    -Dprefix=/usr \
    -Dcheck-update=no \
    -Dmng=disabled \
    -Dwmf=disabled \
    -Dgi-docgen=disabled \
    -Dg-ir-doc=false \
    -Dvector-icons=false \
    -Djavascript=false \
    -Dpython=false \
    -Dlua=false \
    -Dvala-plugins=disabled \
    output

ninja -C output
ninja -C output install

rm -rf "$1/usr/share/gtk-doc"
find "$1" -name '*.la' -type f -exec rm -rf {} +
