#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DCONFIG_WAYLAND=0 \
    -DCONFIG_QT6=0

cmake --build   build
cmake --install build
