#!/bin/sh -e

export DESTDIR="$1"

export LDFLAGS="$LDFLAGS -lexecinfo"

for p in *.patch; do
    patch -p1 < "$p"
done

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_FLAGS="$CFLAGS -ffat-lto-objects -fPIC -w" \
    -DCMAKE_CXX_FLAGS="$CXXFLAGS -ffat-lto-objects -fPIC -w" \
    -DCMAKE_INSTALL_BINDIR=/usr/lib/freecad/bin \
    -DCMAKE_INSTALL_DATADIR=/usr/share/freecad \
    -DCMAKE_INSTALL_DATAROOTDIR=/usr/share \
    -DCMAKE_INSTALL_DOCDIR=/usr/share/freecad/doc \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib/freecad/lib \
    -DCMAKE_INSTALL_PREFIX=/usr/lib/freecad \
    -DBUILD_ENABLE_CXX_STD=C++17 \
    -DBUILD_QT5=ON \
    -DBUILD_FLAT_MESH=ON \
    -DBUILD_FEM_NETGEN=OFF \
    -DFREECAD_USE_EXTERNAL_PIVY=ON \
    -DFREECAD_USE_OCC_VARIANT="Official Version" \
    -DFREECAD_USE_QT_FILEDIALOG=ON \
    -DINSTALL_TO_SITEPACKAGES=ON \
    -DPYTHON_EXECUTABLE=/usr/bin/python3 \
    -DBUILD_WEB=OFF \
    -DBUILD_TEST=OFF \
    -DBUILD_VR=OFF \
    -DBUILD_PLOT=OFF

cmake --build   build
cmake --install build

mkdir -p "$1/usr/bin/"
ln -sf /usr/lib/freecad/bin/FreeCAD "$1/usr/bin/freecad"
ln -sf /usr/lib/freecad/bin/FreeCAD "$1/usr/bin/FreeCAD"
ln -sf /usr/lib/freecad/bin/FreeCADCmd "$1/usr/bin/freecadcmd"
ln -sf /usr/lib/freecad/bin/FreeCADCmd "$1/usr/bin/FreeCADCmd"
