#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
:> tests/meson.build

meson setup \
    -Dprefix=/usr \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dx11=enabled \
    -Dglx=enabled \
    output

ninja -C output
ninja -C output install
