#!/bin/sh -e

export DESTDIR="$1"

# Don't build tests.
:> tests/meson.build

muon setup \
    -Dprefix=/usr \
    -Dx11=enabled \
    -Dglx=enabled \
    output

ninja -C output
muon  -C output install
