#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rootless_modesetting.patch
patch -p1 < cursor.patch

export LDFLAGS="$LDFLAGS -Wl,-z,lazy"
export CFLAGS="$CFLAGS -fcommon"

./configure \
    --prefix=/usr

make
make install
