#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rootless_modesetting.patch

export LDFLAGS="$LDFLAGS -Wl,-z,lazy"
export CFLAGS="$CFLAGS -fcommon"

meson setup \
  -Dprefix=/usr \
  output

ninja -C output
ninja -C output install
