#!/bin/sh -e

export PKG_CONFIG_PATH="/usr/lib/pkgconfig"

./configure \
    --prefix=/usr \
    --libdir=/usr/lib \
    --with-x \
    --enable-win64

make
make \
    prefix="/usr" \
    libdir="/usr/lib" \
    dlldir="/usr/lib/wine" install
