#!/bin/sh -e

export DESTDIR="$1"

export LDFLAGS="$LDFLAGS -Wl,-z,lazy"

meson setup \
    -Dprefix=/usr \
    -Dlibexecdir=/usr/lib \
    -Ddefault-dri=3 \
    -Dxvmc=false \
    -Dvalgrind=false \
    output

ninja -C output
ninja -C output install
