#!/bin/sh -e
# https://download.nvidia.com/XFree86/Linux-x86_64/525.78.01/README/installedcomponents.html

: "${KERNEL_UNAME:=$(uname -r)}"

sh "NVIDIA-Linux-x86_64-${2}-no-compat32.run" --extract-only
cd "NVIDIA-Linux-x86_64-${2}-no-compat32"

# X driver & GLX extension module
install -Dm755 nvidia_drv.so -t "$1/usr/lib/xorg/modules/drivers"
install -Dm755 "libglxserver_nvidia.so.$2" -t "$1/usr/lib/xorg/modules/extensions"
ln -s "libglxserver_nvidia.so.$2" "$1/usr/lib/xorg/modules/extensions/libglxserver_nvidia.so"

# OpenGL
install -Dm644 10_nvidia.json -t "$1/usr/share/glvnd/egl_vendor.d/"

# Vulkan ICD
install -Dm644 nvidia_icd.json -t "$1/usr/share/vulkan/icd.d/"
install -Dm644 nvidia_layers.json -t "$1/usr/share/vulkan/implicit_layer.d/"

# Firmware
install -Dm644 firmware/*.bin -t "$1/usr/lib/firmware/nvidia/$2/"

# Applications profiles
install -Dm644 "nvidia-application-profiles-$2-rc" \
               "nvidia-application-profiles-$2-key-documentation" \
               -t "$1/usr/share/nvidia/"

# Rebuild the nvidia GTK3 library required by nvidia-settings,
# this is to prevent the dangling libraries needed by libnvidia-gtk3
(
    cd ../nvidia-settings-src

    for p in ../*nvidia-settings*.patch; do
        patch -p1 < "$p"
    done

    cd src

	# Makefile does not provide a way to compile 
	# it directly, so we 'install' it; which depends on it
    make PREFIX=/usr BUILD_GTK3LIB=1 \
         EXTRA_CFLAGS='-Wno-deprecated-declarations' \
         NVIDIA_GTKLIB_install
)

for bin in modprobe smi debugdump bug-report.sh settings; do
    install -Dm755 "nvidia-${bin}" -t "$1/usr/bin/"

    [ -f "nvidia-${bin}.1.gz" ] || continue
    install -Dm644 "nvidia-${bin}.1.gz" -t "$1/usr/share/man/man1/"
done

chmod 4755 "$1/usr/bin/nvidia-modprobe"

libs="
libEGL_nvidia libGLESv1_CM_nvidia libGLESv2_nvidia libGLX_nvidia
libnvidia-tls libnvidia-glcore libnvidia-glsi libnvidia-glvkspirv
libnvidia-fbc libnvidia-eglcore libnvidia-encode libnvcuvid libcuda
libnvidia-ml
"

# Copy & Proper SONAME links
# /usr/lib/libGLX_nvidia.so.525.105.17 -> /usr/lib/libGLX_nvidia.so.0
# /usr/lib/libGLX_nvidia.so.0 -> /usr/lib/libGLX_nvidia.so
for lib in $libs; do
    lib="${lib}.so.${2}"
    cp "$lib" "$1/usr/lib/"
    soname="$1/usr/lib/$(readelf -d "$lib" | awk -F'[][]' '/SONAME/ {print $2}')"
    base=${soname%%.so*}
    [ -e "$soname" ] || ln -sf "${lib##*/}" "${soname}"
    [ -e "$base" ] || ln -sf "${soname##*/}" "${base}.so"
done

# kernel modules
cd kernel
make modules
make INSTALL_MOD_PATH="$1/usr" INSTALL_MOD_STRIP=1 modules_install
rm -f "$1/usr/lib/modules/"*"/modules."*
