#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dmandir=/usr/share/man \
    -Dalsa=enabled \
    -Dlibmpv=true \
    -Dwayland=disabled \
    -Dx11=enabled \
    output

ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
