#!/bin/sh -e

export DESTDIR="$1"

# Setup docutils to generate manual pages.
{
    cd docutils

    python3 setup.py build
    python3 setup.py install \
        --root="$PWD/../dist"

    cd ../dist/usr/lib/python*/site-packages

    PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

    cd -; cd ..
    export PATH="$PWD/dist/usr/bin:$PATH"
    export PYTHONPATH
}

meson setup \
    -Dprefix=/usr \
    -Dmandir=/usr/share/man \
    -Dalsa=enabled \
    -Dlibmpv=true \
    -Dwayland=disabled \
    -Dx11=enabled \
    output

ninja -C output
ninja -C output install

rm -rf \
    "$1/usr/share/zsh" \
    "$1/usr/share/bash-completion"
