#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -w"
export CXXFLAGS="$CXXFLAGS -w"

git submodule update --init

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DUSE_SYSTEM_CURL=ON \
    -DUSE_SYSTEM_FFMPEG=ON \
    -DUSE_SYSTEM_LIBPNG=ON \
    -DUSE_SYSTEM_ZLIB=ON

cmake --build   build
cmake --install build
