#!/bin/sh -e

export DESTDIR="$1"


make
make PREFIX=/usr install
make PREFIX=/usr -C gadgets  install

install -Dm644 README  "$1/usr/share/doc/dzen/README"
install -Dm644 CREDITS "$1/usr/share/doc/dzen/CREDITS"
install -Dm644 LICENSE "$1/usr/share/licenses/dzen/LICENSE"
