#!/bin/sh -e

sed "/subdir('test')/d" meson.build > _
mv -f _ meson.build

kiss list gobject-introspection && intro="true"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dgtk_doc=false \
    -Dintrospection="${intro:-false}" \
    -Dvapi=true \
    -Dpython3=false \
    . output

ninja -C output
ninja -C output install
