#!/bin/sh -e

sed "/subdir('test')/d" meson.build > _
mv -f _ meson.build

if kiss list gobject-introspection; then
    intro="true"
fi
if kiss list vala; then
    vapi="true"
fi
meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    -Dgtk_doc=false \
    -Dintrospection="${intro:-false}" \
    -Dvapi=${vapi:-false} \
    -Dpython3=false \
    . output

ninja -C output
ninja -C output install
