#!/bin/sh -e

export DESTDIR="$1"

# Chnage the follow hints from numbers to letters on the home row
sed -E \
    "s~(setting_add\(c, \"hint-keys\", TYPE_CHAR, &\")0123456789~\1asdfghjkl~" \
    src/setting.c > _
mv -f _ src/setting.c

make PREFIX=/usr
make PREFIX=/usr install
