#!/bin/sh -e

: > po/meson.build

command -v openssl && openssl=true

meson setup \
    -Dprefix=/usr \
    -Dwith-python=false \
    -Dwith-perl=false \
    -Dwith-lua=false \
    -Dwith-fishlim="${openssl:-false}" \
    -Dwith-sysinfo=false \
    -Dwith-checksum=false \
    output

ninja -C output
ninja -C output install
