#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < fix-W_EXITCODE.patch

pkg-config --exists gnutls && GNUTLS=true

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddocs=false \
    -Dgir=false \
    -Dfribidi=false \
    -Dicu=false \
    -Dvapi=false \
    -Dgnutls="${GNUTLS:-false}" \
    -D_systemd=false \
    output

ninja -C output
ninja -C output install
