#!/bin/sh -e

export DESTDIR="$1"


export CFLAGS="$CFLAGS -fcommon"

cmake \
    -Bbuild \
    -DFREEGLUT_BUILD_STATIC_LIBS=OFF \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=None

cmake --build   build
cmake --install build
