#!/bin/sh -e

err() {
    echo $@
    exit 1
}

command -v inkscape && {
    err "Uninstall inkscape to avoid a circular dependency"
}

sed -e "/INKSCAPE_CXX_FLAGS \"-Werror=format/d" \
    CMakeScripts/DefineDependsandFlags.cmake > _
mv -f _ CMakeScripts/DefineDependsandFlags.cmake

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_VERBOSE_MAKEFILE=ON \
    -DENABLE_POPPLER_CAIRO=ON \
    -DPOPPLER_INCLUDE_DIR=/usr/include/poppler \
    -DBUILD_SHARED_LIBS=True \
    -DBUILD_STATIC_LIBS=False \
    -DBUILD_TESTS=OFF \
    -DWITH_GNOME_VFS=OFF \
    -DWITH_NLS=OFF \
    -DWITH_DBUS=OFF \
    -DWITH_LIBCDR=OFF \
    -DWITH_LIBVISIO=OFF \
    -DWITH_LIBWPG=OFF \
    -DWITH_IMAGE_MAGICK=OFF

cmake --build   build
cmake --install build
