#!/bin/sh -e

export DESTDIR="$1"

./configure \
    --prefix=/usr \
    --mandir=/usr/share/man \
    --localstatedir=/var/games \
    --disable-motif \
    --enable-athena \
    --disable-gtk
make
make install
