#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dintrospection=false \
    -Dgtk_doc=false \
    -Dsystemd=disabled \
    -Dssh_agent=false \
    output

ninja -C output
ninja -C output install
