#!/bin/sh -e

export DESTDIR="$1"

# Disable nls.
: > po/meson.build

#pkg-config --exists gobject-introspection-1.0 && gi=true

meson setup \
    -Dprefix=/usr \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dintrospection=${gi:-false} \
    -Dgtk_doc=false \
    -Dsystemd=disabled \
    -Dssh_agent=false \
    output

ninja -C output
ninja -C output install
