#!/bin/sh -e

export DESTDIR="$1"


# Disable documentation, since it depends on `sphinx-build`.
rm -- doc/CMakeLists.txt
sed "s/BUILD_DOC/false/g" CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr

cmake --build   build
cmake --install build
