#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < no-uuid.patch

# Don't build tests.
ed data/meson.build > /dev/null << EOF
/subdir('tests')/d
w
q
EOF

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddep11=false \
    -Dman=false \
    -Dstemmer=false \
    -Dintrospection=false \
    -Drpm=false \
    output

ninja -C output
ninja -C output install
