#!/bin/sh -e

export DESTDIR="$1"

if ! patch --help 2>&1 | grep gnu; then
    echo "Switch to gnu patch:"
    echo "# kiss a patch /usr/bin/patch"
    exit 1
fi

patch -p1 < no-uuid.patch

# Don't build tests.
sed "/subdir('tests')/d" data/meson.build > _
mv -f _ data/meson.build

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddep11=false \
    -Dman=false \
    -Dintrospection=false \
    -Drpm=false \
    output

ninja -C output
ninja -C output install
