#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
    patch -p1 < "$p"
done

# Don't build tests and po.
sed -e "/subdir('tests')/d" \
    -e "/subdir('po')/d" meson.build > _
mv -f _ meson.build

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddep11=false \
    -Dman=false \
    -Dstemmer=false \
    -Dintrospection=false \
    -Drpm=false \
    output

ninja -C output
muon  -C output install
