#!/bin/sh -e

unzip "irrlicht-$2.zip?no-extract"

cd "irrlicht-$2"

sed -r '/^#define _IRR_USE_NON_SYSTEM_(JPEG_LIB|LIB_PNG|ZLIB|BZLIB)_/d' include/IrrCompileConfig.h > _
mv -f _ include/IrrCompileConfig.h
sed -r '/^(ZLIB|JPEGLIB|LIBPNG|BZIP2)OBJ/d' source/Irrlicht/Makefile > _
mv -f _ source/Irrlicht/Makefile
sed -r '/^sharedlib: LDFLAGS/s,\r?$, -lz -ljpeg -lpng -lz -lbz2,' source/Irrlicht/Makefile > _
mv -f _ source/Irrlicht/Makefile

rm -rf source/Irrlicht/bzip2
rm -rf source/Irrlicht/jpeglib
rm -rf source/Irrlicht/libpng
rm -rf source/Irrlicht/zlib

cd source/Irrlicht

make NDEBUG=1 sharedlib

sed "/^INSTALL_DIR/s:=.*:=$1/usr/lib:" Makefile > _
mv -f _ Makefile

make install

chmod 644 "$1"/usr/include/irrlicht/*

ln -s "libIrrlicht.so.$2" "$1/usr/lib/libIrrlicht.so.1"
