#!/bin/sh -e

patch -p1 < glew.patch

# Fix main executable installation directory
sed -i 's/\$PREFIX\/games/\$PREFIX\/bin/g' SConstruct

scons -j "$(($(nproc)-1))"
scons DESTDIR=$1 PREFIX=/usr install
