#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -fno-omit-frame-pointer"

for p in "execinfo.c&#include <sys/types.h>" "stacktraverse.c&#include <stddef.h>" "test.c&#include <stdio.h>"; do
    sed -E "s~(${p##*&})~#define _GNU_SOURCE\n\1~" "${p%%&*}" > _
    mv -f _ "${p%%&*}"
done

for patch in *.patch; do
    patch -p1 < "$patch"
done

make
for f in execinfo.h stacktraverse.h libexecinfo.a libexecinfo.so.1; do
    case "$f" in
        *.h) install -Dm755 "$f" "$1/usr/include/$f" ;;
        *.a | *.so.*) install -Dm755 "$f" "$1/usr/lib/$f" ;;
    esac
done
ln -s /usr/lib/libexecinfo.so.1 "$1"/usr/lib/libexecinfo.so
