#!/bin/sh -e

export DESTDIR="$1"


export CXXFLAGS="$CXXFLAGS -std=c++11"

sed -e "/subdir('tests')/d" \
    -e "/subdir('demos/gtk-demo')/d" meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    . output

ninja -C output
ninja -C output install
