#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -w -DALWAYS_ROOT=1"
export CXXFLAGS="$CXXFLAGS -w -DALWAYS_ROOT=1"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --enable-shared \
    --enable-client=gtk3 \
    --enable-fcmp=gtk3 \
    --enable-fcdb=sqlite3 \
    --enable-aimodules \
    --enable-debug=no

make
make install
