#!/bin/sh -e

# switch webkit version to 4.1, if libsoup3 were used to build webkit
if pkg-config --exist webki2gtk-4.1; then
	sed 's/4.0/4.1/' makefile > _
	mv -f _ makefile
fi

make PREFIX=/usr
make PREFIX=/usr install
