#!/bin/sh -e

export DESTDIR="$1"

# Swap to shell script instead of perl script
# for conversion of rules files. See files/xml2lst.
sed 's/xml2lst\.pl/xml2lst/' rules/meson.build > _
mv -f _ rules/meson.build

# Remove po/ dir, and usless i18n module.
sed -e "/subdir('po')/d" -e "/i18n/d" meson.build > _
mv -f _ meson.build

muon setup \
    -Dprefix=/usr \
    -Dcompat-rules=true \
    -Dxorg-rules-symlinks=true \
    -Dxkb-base="/usr/share/X11/xkb" \
    output

ninja -C output
muon -C output install
