#!/bin/sh -e

export DESTDIR="$1"

: > tests/meson.build

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddocs=false \
    -Dintrospection=false \
    output

ninja -C output
ninja -C output install
