#!/bin/sh -e

export DESTDIR="$1"

: > tests/meson.build

pkg-config --exists gobject-introspection-1.0 && gi=true

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Ddocs=false \
    -Dintrospection="${gi:-false}" \
    output

ninja -C output
ninja -C output install
