#!/bin/sh -e

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_WIIUSE=OFF \
    -DBUILD_RECORDER=0

cmake --build   build
cmake --install build

rm -rf "$1/usr/share/metainfo"
