#!/bin/sh -e

export DESTDIR="$1"

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=x11 \
    -Dglx=auto \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dvulkan-drivers='' \
    -Dglvnd="${glvnd_enabled:-true}" \
    output

ninja -C output
ninja -C output install
