#!/bin/sh -e

export DESTDIR="$1"

# rust_std is not (yet?) supported by muon, and we should try
# to avoid a hard rust dependency here if possible.
sed "s/, 'rust_std=2021'//" meson.build > _
mv -f _ meson.build

# To prevent the need for users to fork the mesa package to add
# libglvnd support, the below code checks for its availability
# and enables it if present. ie: install glvnd, rebuild mesa.
pkg-config --exists libglvnd || glvnd_enabled=false

# LLVM _must_ be built with LLVM_ENABLE_RTTI enabled, this patch
# removes the check for it due to it's requirement for CMake
patch -p1 < no-llvm-rtti-check.patch

muon setup \
    -Dprefix=/usr \
    -Dbuildtype=release \
    -Dglx-read-only-text=true \
    -Dplatforms=x11 \
    -Dglx=auto \
    -Degl=enabled \
    -Dvalgrind=false \
    -Dzstd=disabled \
    -Dglvnd="${glvnd_enabled:-true}" \
    -Dvideo-codecs=vc1dec,h264dec,h264enc,h265dec,h265enc \
    -Dvulkan-drivers='' \
    output

ninja -C output
muon  -C output install
