#!/bin/sh -e

printf "NOTE: It is HIGHLY recommended to build this package with sane build flags and 'ccache' enabled!\n"

# Patches relating to libc are conditionally applied to avoid breakage.
kiss list musl && {
    for patch in musl-*.patch; do
        patch -p1 < "$patch"
    done
}

# Saves me from having to fork this package just for 2 patches.
kiss list glibc && {
    for patch in glibc-*.patch; do
        patch -p1 < "$patch"
    done
}

# Glob includes the libstdc++ patchset aswell.
for patch in chromium-*.patch; do
    patch -p1 < "$patch"
done

python ungoogled-chromium/utils/prune_binaries.py \
    ./ ungoogled-chromium/pruning.list

# Bypass the Python script and apply patches ourselves to avoid GNU patch.
while read -r patch; do
    [ "$patch" ] || continue
    patch -p1 < "ungoogled-chromium/patches/$patch"
done < ungoogled-chromium/patches/series

python ungoogled-chromium/utils/domain_substitution.py apply \
    -r ungoogled-chromium/domain_regex.list \
    -f ungoogled-chromium/domain_substitution.list \
    -c domainsubcache.tar.gz ./

mkdir -p third_party/node/linux/node-linux-x64/bin
ln -s /usr/bin/node third_party/node/linux/node-linux-x64/bin/

# Facilitate deterministic builds (taken from build/config/compiler/BUILD.gn)
export CFLAGS="$CFLAGS -Wno-builtin-macro-redefined"
export CXXFLAGS="$CXXFLAGS -Wno-builtin-macro-redefined"
export CPPFLAGS="$CPPFLAGS -D__DATE__=  -D__TIME__=  -D__TIMESTAMP__="

export CC="${CC:-cc}"
export CXX="${CXX:-c++}"
export AR="${AR:-ar}"
export NM="${NM:-nm}"

# Allow building against system libraries in official builds.
sed 's/OFFICIAL_BUILD/GOOGLE_CHROME_BUILD/' \
    tools/generate_shim_headers/generate_shim_headers.py > _
mv -f _ tools/generate_shim_headers/generate_shim_headers.py

# Missing include required for std::find()
sed '/<vector>/a #include <algorithm>' \
    ui/ozone/public/platform_gl_egl_utility.h > _
mv -f _ ui/ozone/public/platform_gl_egl_utility.h

# Useless internal glibc header include.
# stdint.h is already included by stuff and is enough to define intN_t types.
sed '/<bits\/stdint-intn.h>/d' \
    ui/ozone/platform/wayland/host/wayland_window.cc > _
mv -f _ ui/ozone/platform/wayland/host/wayland_window.cc

# compile gn early, so it can be used to generate gni stuff.
./tools/gn/bootstrap/bootstrap.py --skip-generate-buildfiles

# ffmpeg: abi will break soon
# freetype: syslib broken
# harfbuzz-ng: syslib broken
# icu: Breakage on updates.
# libevent: Random freezes with javascript.
# libjpeg: Build failure
# libpng: KISS builds with APNG patch (https://crbug.com/752403#c10).
# libvpx: Broken ?
# libxml: bundle as it's only required by browsers
# libxslt: bundle as it's only requred by browsers
# zlib: KISS build without 'minizip'.
#    libjpeg
#    libjpeg_turbo
system="
    flac
    fontconfig
    libdrm
    libwebp
    opus
"

# remove build scripts for system provided dependencies - basically does the
# same as the bundled script to remove bundled libs, but this way we don't
# have to list the remaining libs.
for lib in $system; do
    find . -type f -path "*third_party/$lib/*" \
        \! -path "*third_party/$lib/chromium/*" \
        \! -path "*third_party/$lib/google/*" \
        \! -path "./base/third_party/icu/*" \
        \! -path "./third_party/pdfium/third_party/freetype/include/pstables.h" \
        \! -path "./third_party/harfbuzz-ng/utils/hb_scoped.h" \
        \! -name "*.gn" \
        \! -name "*.gni" \
        \! -name "*.isolate" \
        \! -name "*.py" \
        -exec rm -rf {} +
done

# switch to system provided dependencies.
# shellcheck disable=2086
./build/linux/unbundle/replace_gn_files.py --system-libraries $system

./third_party/libaddressinput/chromium/tools/update-strings.py

# 'clang' builds are untested but should most likely work fine with our flags.
case $("$CC" --version) in (*clang*)
    clang=true
esac

kiss list libva && vaapi=true
kiss list pipewire && pipewire=true

conf="
    angle_enable_null=true
    angle_enable_swiftshader=true
    blink_enable_generated_code_formatting=false
    blink_symbol_level=0
    clang_use_chrome_plugins=false
    custom_toolchain=\"//build/toolchain/linux/unbundle:default\"
    enable_swiftshader=false
    enable_swiftshader_vulkan=false
    enable_vr=false
    enable_widevine=false
    fatal_linker_warnings=false
    ffmpeg_branding=\"Chrome\"
    host_toolchain=\"//build/toolchain/linux/unbundle:default\"
    is_cfi=false
    is_clang=${clang:-false}
    is_debug=false
    is_official_build=true
    link_pulseaudio=false
    ozone_platform_wayland=false
    ozone_platform_x11=true
    proprietary_codecs=true
    rtc_build_examples=false
    rtc_use_pipewire=${pipewire:-false}
    rtc_use_x11=true
    rtc_use_x11_extensions=true
    symbol_level=0
    use_allocator=\"none\"
    use_allocator_shim=false
    use_atk=false
    use_cups=false
    use_custom_libcxx=false
    use_dbus=false
    use_gnome_keyring=false
    use_gold=false
    use_kerberos=false
    use_libpci=false
    use_lld=false
    use_pulseaudio=false
    use_sysroot=false
    use_system_harfbuzz=true
    use_thin_lto=false
    use_vaapi=${vaapi:-false}
    use_x11=true
    use_xkbcommon=false
    build_with_tflite_lib=false
    chrome_pgo_phase=0
    disable_fieldtrial_testing_config=true
    enable_hangout_services_extension=false
    enable_js_type_check=false
    enable_mdns=false
    enable_mse_mpeg2ts_stream_parser=true
    enable_nacl=false
    enable_nacl_nonsfi=false
    enable_one_click_signin=false
    enable_reading_list=false
    enable_remoting=false
    enable_reporting=false
    enable_service_discovery=false
    exclude_unwind_tables=true
    google_api_key=\"\"
    google_default_client_id=\"\"
    google_default_client_secret=\"\"
    safe_browsing_mode=0
    treat_warnings_as_errors=false
    use_official_google_api_keys=false
    use_unofficial_version_number=false
"

out/Release/gn gen out/Release --args="$conf"

# Attempt to increase file descriptor limit
# as build may exhaust default (1024).
#
# -n is non-POSIX hence we "attempt".
# shellcheck disable=2039
ulimit -n 4096 2>/dev/null || :

ninja -C out/Release chrome

# Package the monster.
mkdir -p "$1/usr/bin" \
         "$1/usr/lib/chromium/locales"

cp chromium.sh "$1/usr/bin/chromium"

# Fix for Xorg hardware acceleration.
# https://github.com/ehawkvu/kiss-xorg/issues/2
for lib in libEGL.so libGLESv2.so; do
    install -Dm755 "out/Release/$lib" "$1/usr/lib/chromium"
done

cd out/Release

cp chrome "$1/usr/lib/chromium/chromium"
cp locales/*.pak "$1/usr/lib/chromium/locales/"
cp -- icudtl.dat *.bin *.pak "$1/usr/lib/chromium/"
