#!/bin/sh -e

./configure \
    --prefix=/usr \
    --disable-cairo \
    --disable-rsvg \
    --disable-xmu \
    --disable-fribidi \
    --disable-nls \
    --disable-xpm \
    --disable-xbm

make
make DESTDIR="$1" install
