#!/bin/sh -e

export DESTDIR="$1"
export CFLAGS="$CFLAGS -D_POSIX_C_SOURCE=200809L"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_XPM=OFF

cmake --build   build
cmake --install build
