#!/bin/sh -e

export DESTDIR="$1"


sed 's/pthread-stubs //' configure > _
mv -f _ configure
chmod +x configure

./configure \
    --prefix=/usr

make
make install

# Remove library documentation.
# False positive.
# shellcheck disable=2115
rm -rf "$1/usr/share"
