#!/bin/sh -ex

export DESTDIR="$1"

patch -p1 < muon.patch

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dtls_check=false \
    -Dtests=false \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    output

ninja -C output
muon  -C output install
