#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dlocalstatedir=/var \
    -Dtls_check=false \
    -Dvapi=disabled \
    -Dgssapi=disabled \
    -Dbrotli=disabled \
    -Dsysprof=disabled \
    output

ninja -C output
ninja -C output install
