#!/bin/sh -e

export DESTDIR="$1"

sed "/execinfo.h/d" CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DCMAKE_BUILD_TYPE=None \
    -DENABLE_CDF5=ON \
    -DENABLE_DAP_LONG_TESTS=OFF \
    -DENABLE_EXAMPLE_TESTS=OFF \
    -DENABLE_EXTRA_TESTS=OFF \
    -DENABLE_FAILING_TESTS=OFF \
    -DENABLE_FILTER_TESTING=OFF \
    -DENABLE_LARGE_FILE_TESTS=OFF \
    -DENABLE_HDF4_FILE_TESTS=OFF \
    -DENABLE_DAP_REMOTE_TEST=OFF \
    -DENABLE_TESTS=OFF

cmake --build   build
cmake --install build
