#!/bin/sh -e

# Remove gettext dependency.
sed "/subdirectory(po)/d;/find_package(Gettext/d" CMakeLists.txt > _
mv -f _ CMakeLists.txt

# The desktop file requires gettext, so we don't build it.
sed "/subdirectory(desktop)/d" CMakeLists.txt > _
mv -f _ CMakeLists.txt

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_MAINTAINER_TOOLS=TRUE \
    -DENABLE_FONTFORGE_EXTRAS=TRUE \
    -DENABLE_DOCS=OFF \
    -DENABLE_LIBSPIRO=OFF \
    -DENABLE_CODE_COVERAGE=OFF \
    -DENABLE_LIBREADLINE=OFF \
    -DUNIX=TRUE

cmake --build   build
cmake --install build
