#!/bin/sh -e

export CXXFLAGS="$CXXFLAGS -fPIC "
export CFLAGS="$CFLAGS -fPIC "

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release

cmake --build   build
cmake --install build
