#!/bin/sh -e

export DESTDIR="$1"

# Make xauth optional at runtime.
cmd='command -v xauth >/dev/null \&\&'
sed "s#\(enable_xauth\)=1#$cmd&||\1=0#" startx.in > _
mv -f _ startx.in

./configure \
    --prefix=/usr \
    --with-xinitdir=/etc/X11/xinit

make
make install
