#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < add-av_stream_get_first_dts-for-chromium.patch

./configure \
    --cc="$CC" \
    --cxx="$CXX" \
    --prefix=/usr \
    --disable-debug \
    --disable-libxml2 \
    --disable-static \
    --enable-gpl \
    --enable-libass \
    --enable-libdrm \
    --enable-libmp3lame \
    --enable-libopus \
    --enable-libvorbis \
    --enable-libvpx \
    --enable-libwebp \
    --enable-libx264 \
    --enable-libx265 \
    --enable-libxvid \
    --enable-nonfree \
    --enable-libtls \
    --enable-shared \
    --enable-version3 \
    --x86asmexe=nasm

make
make install

rm -rf "$1/usr/share/ffmpeg/examples"
