#!/bin/sh -e

export DESTDIR="$1"

sed "s/if \`\$INTLTOOL_PERL -e/if test -z \`\$INTLTOOL_PERL -e/g" configure > _
mv -f _ configure
chmod +x configure

./configure \
    --prefix=/usr \
    --localstatedir=/var \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --disable-nls

make
make install
