#!/bin/sh -e

export DESTDIR="$1"

autoreconf -vif

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-ipv6 \
    --enable-tls

make
make install
