#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < openssl.patch

aclocal
automake --add-missing
autoreconf -fi

export CFLAGS="$CFLAGS -D_GNU_SOURCE -fcommon"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --enable-ipv6 \
    --enable-ssl
make
make install
