#!/bin/sh -e

export DESTDIR="$1"

for p in *.patch; do
    patch -p1 < "$p"
done

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=None \
    -DBUILD_TESTS=OFF \
    -DUSE_PYTHON_VERSION=3

# This is extraoridinarily hacky...
# But there is no other way to get this thing to build properly.
# This is because the two are mutual dependencies of each other.
cmake --build   build || :
cmake --install build || :
