#!/bin/sh -e

export DESTDIR="$1"


meson \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dwith_wayland=no \
    -Dwith_x11=yes \
    -Dwith_glx=yes \
    . output

ninja -C output
ninja -C output install
