#!/bin/sh -e

export DESTDIR="$1"

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dwith_wayland=no \
    -Dwith_x11=yes \
    -Dwith_glx=yes \
    output

ninja -C output
muon -C output install
