#!/bin/sh -e

# Build fails with clang due to -Werror (forced on) and
# -Wunused-command-line-argument which is triggered by.
# the below CFLAGS.
export CFLAGS="-Wno-unused-command-line-argument $CFLAGS"

export DESTDIR="$1"

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --libexecdir=/usr/lib \
    -Ddebug-gui=false \
    -Ddocumentation=false \
    -Dtests=false \
    -Dlibwacom=false \
    . output

ninja -C output
ninja -C output install
