#!/bin/sh -e

for f in yasm fribidi ; do (
    cd "$f"
    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
) done

export PATH="$PWD/junk/bin:$PATH"

./configure \
    --prefix=/usr \
    --disable-vidix \
    --disable-ossaudio

make
make install DESTDIR="$1"

install -Dm0644 etc/example.conf "$1/etc/mplayer/mplayer.conf"
