#!/bin/sh -e

export DESTDIR="$1"

mkdir -p path
ln -s /usr/bin/true path/docbook2x-man
export PATH="$PWD/path:$PATH"

# the build includes execinfo in some places, but patching it is quite hard
# due to self-patching build system
cat > include/execinfo.h <<-EOF
/* nothing */
EOF

NOCONFIGURE=1 ./autogen.sh

# https://bugs.documentfoundation.org/show_bug.cgi?id=78174
# https://gcc.gnu.org/bugzilla/show_bug.cgi?id=64812
# gcc with -Os will produce "undefined reference to non-virtual thunk to XXX"
# errors. workaround by forcing -O2.
# also this thing is huge and O2 makes more sense.
#export CFLAGS="-O2 $CFLAGS"
#export CPPFLAGS="-O2 $CFLAGS"
#export CXXFLAGS="-O2 $CFLAGS"

export CC=clang
export CXX=clang++

# force c++17 here since otherwise it's not set for abseil conftest
export CXXFLAGS="$CXXFLAGS -std=c++17"

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --localstatedir=/var \
    --disable-dependency-tracking \
    --disable-fetch-external \
    --disable-online-update \
    --enable-python=system \
    --enable-release-build \
    --enable-split-app-modules \
    --with-external-dict-dir=/usr/share/hunspell \
    --with-external-hyph-dir=/usr/share/hyphen \
    --with-external-tar="$PWD" \
    --with-lang="" \
    --with-system-dicts \
    --with-system-libs \
    --with-system-zxing \
    --with-tls=nss \
    --with-vendor="KISS Linux" \
    --without-fonts \
    --without-junit \
    --without-myspell-dicts \
    --without-system-dragonbox \
    --without-system-jars \
    --without-system-libcmis \
    --without-system-libfixmath \
    --without-system-sane \
    --without-system-zxing \
    --without-doxygen \
    --without-docbook \
    --disable-coinmp \
    --disable-firebird-sdbc \
    --disable-lpsolve \
    --enable-gtk3 \
    --disable-gtk3-kde5 \
    --disable-gtk4 \
    --disable-kf5 \
    --disable-odk \
    --disable-qt5 \
    --disable-qt6 \
    --disable-skia \
    --without-java

make build
# build libreofficekit
cd libreofficekit && make

make distro-pack-install
