#!/bin/sh -e

export DESTDIR="$1"


export CXXFLAGS="$CXXFLAGS -DGLM_ENABLE_EXPERIMENTAL -DU_USING_ICU_NAMESPACE=1"

# Libreoffice needs `cp` from GNU coreutils.
if ! [ "$(kiss owns /usr/bin/cp)" = coreutils ]; then
    kiss alternatives coreutils /usr/bin/cp
fi

mv skia-freetype2.11.diff external/skia/"skia-freetype2.11.patch"

for patch in *.patch; do
    patch -p1 < "$patch"
done

NOCONFIGURE=1 ./autogen.sh

# Add support for musl in configure script.
sed 's;linux-gnu\*;linux-gnu*|linux-musl*;g' configure > _
mv -f _ configure
chmod +x configure

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --sbindir=/usr/bin \
    --bindir=/usr/bin \
    --mandir=/usr/share/man \
    --infodir=/usr/share/info \
    --with-vendor='KISS Linux' \
    --with-lang="" \
    --with-tls=openssl \
    --without-fonts \
    --without-java \
    --without-junit \
    --without-krb5 \
    --without-gssapi \
    --without-system-dicts \
    --disable-avahi \
    --disable-cups \
    --disable-coinmp \
    --disable-dbus \
    --disable-dependency-tracking \
    --disable-firebird-sdbc \
    --disable-kf5 \
    --disable-ldap \
    --disable-librelogo \
    --disable-lpsolve \
    --disable-mariadb-sdbc \
    --disable-online-update \
    --disable-postgresql-sdbc \
    --disable-python \
    --disable-qt5 \
    --disable-qt6 \
    --disable-report-builder \
    --disable-skia \
    --enable-gtk3 \
    --enable-openssl \
    --enable-release-build \
    --with-system-bzip2 \
    --with-system-boost \
    --with-system-cairo \
    --with-system-curl \
    --with-system-expat \
    --with-system-epoxy \
    --with-system-harfbuzz \
    --with-system-icu \
    --with-system-graphite \
    --with-system-gpgme \
    --with-system-jpeg \
    --with-system-libxml \
    --with-system-libpng \
    --with-system-lcms2 \
    --with-system-libatomic-ops \
    --with-system-neon \
    --with-system-nss \
    --with-system-openssl \
    --with-system-poppler \
    --with-system-zlib

# Disable slowcheck target.
sed "/gb_Top_MODULE_CHECK_TARGETS /s/ slowcheck//" Makefile > _
mv -f _ Makefile

make build-nocheck
make PREFIXDIR=/usr distro-pack-install

rm -rf -- "$1/usr/lib32"
