#!/bin/sh -e

export DESTDIR="$1"

# Disable building tests.
: > test/meson.build

muon setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dpkg_config_path=/usr/lib/pkgconfig \
    -Dx11=true \
    output

ninja -C output
muon -C output install
