#!/bin/sh -e

export DESTDIR="$1"


git submodule update --init extlib/libdxfrw extlib/mimalloc

cmake -B build \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DENABLE_TESTS=OFF \
    -DENABLE_COVERAGE=OFF \
    -DENABLE_GUI=ON

cmake --build   build
cmake --install build
