#!/bin/sh -e

export DESTDIR="$1"

sed -e "/subdir('tests')/d" \
    -e "/subdir('po')/d" meson.build > _
mv -f _ meson.build

pkg-config --exists gobject-introspection-1.0 && intro=true

meson setup \
    -Dprefix=/usr \
    -Dsysconfdir=/etc \
    -Dmandir=/usr/share/man \
    -Dlocalstatedir=/var \
    -Dbuildtype=plain \
    -Ddocs=false \
    -Dintrospection="${intro:-false}" \
    -Dvapigen=disabled \
    -Dgdk-pixbuf=disabled \
    -Dlibav=disabled \
    output

ninja -C output
ninja -C output install
