#!/bin/sh -e

export DESTDIR="$1"


# Use local glm headers.
for f in src/*.?pp; do
    sed 's|<glm/glm\.hpp>|"../glm/glm/glm.hpp"|' "$f" > _
    mv -f _ "$f"
done

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_BUILD_TYPE=Release \
    -DGLM_INCLUDE_DIR=./glm

cmake --build   build
cmake --install build
