#!/bin/sh -e

export DESTDIR="$1"


CFLAGS_FOR_BUILD=-fPIC \
./configure \
    --prefix=/usr \
    --without-xmlto \
    --disable-specs \
    --disable-static

make
make install

# Remove library documentation.
rm -rf "$1/usr/share/man/man3"
