#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < remove-usage-of-fstat64.patch

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -Dbuild_doc:BOOL=OFF \
    -Dbuild_wizard:BOOL=OFF

cmake --build   build
cmake --install build
