#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rootless_modesetting.patch

# Building with GCC 12.1 fails because of this warning, so disable it.
export CFLAGS="-Wno-error=array-bounds $CFLAGS"

# Disable tests.
: > test/meson.build

meson setup \
    -Dprefix='/usr' \
    -Dlocalstatedir='/var' \
    -Dsystemd_logind=false \
    -Dglx=true \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Dglamor=true \
    -Dxorg=true \
    -Dxephyr=false \
    -Dxdmcp=false \
    -Ddefault_font_path=/usr/share/fonts \
    -Dsecure-rpc=false \
    output

ninja -C output
ninja -C output install
