#!/bin/sh -e

patch -p1 < rootless_modesetting.patch

fonts=/usr/share/fonts
meson \
    --prefix=/usr \
    --buildtype=release \
    -Dxorg=true \
    -Dsystemd_logind=false \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Ddefault_font_path="$fonts/100dpi:unscaled,$fonts/75dpi:unscaled,$fonts/OTF,$fonts/TTF,$fonts/Type1,$fonts/misc" \
    -Dxdmcp=false \
    -Dsecure-rpc=false \
    -Dsha1=libcrypto \
    . output

ninja -C output
ninja -C output install
