#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < rootless_modesetting.patch

meson \
    -Dprefix='/usr' \
    -Dlocalstatedir='/var' \
    -Dsystemd_logind=false \
    -Dglx=true \
    -Ddri1=true \
    -Ddri2=true \
    -Ddri3=true \
    -Dglamor=true \
    -Dxorg=true \
    -Dxdmcp=false \
    -Ddefault_font_path=/usr/share/fonts \
    -Dsecure-rpc=false \
    . output

ninja -C output
ninja -C output install
