#!/bin/sh -e

export DESTDIR="$1"


: > tests/meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    . output

ninja -C output
ninja -C output install
