#!/bin/sh -e

sed "/subdir('tests')/d" meson.build > _
mv -f _ meson.build

meson \
    --prefix=/usr \
    --sysconfdir=/etc \
    --mandir=/usr/share/man \
    --localstatedir=/var \
    --buildtype=plain \
    . output

ninja -C output
ninja -C output install
