#!/bin/sh -e

export DESTDIR="$1"

# Setup docutils to generate manual pages.
{
    cd docutils

    python setup.py build
    python setup.py install \
        --root="$PWD/../dist"

    cd ../dist/usr/lib/python*/site-packages

    PYTHONPATH=$PWD:$(python -c "import sys;print(':'.join(sys.path))")

    cd -; cd ..
    export PATH="$PWD/dist/usr/bin:$PATH"
    export PYTHONPATH
}

meson setup \
    -Dprefix=/usr \
    -Dvalgrind=disabled \
    output

ninja -C output
ninja -C output install
