#!/bin/sh -e

for p in *.patch; do
    patch -p1 < "$p"
done

# Build autoconf 2.13 for Librewolf's sole use.
# See: https://bugzilla.mozilla.org/show_bug.cgi?id=104642
(
    cd autoconf2.13

    ./configure \
        --prefix="$PWD/../junk" \
        --program-suffix=-2.13

    make
    make install
)

if ! command -v yasm; then (
    cd yasm

    ./configure \
        --prefix=/

    make
    make DESTDIR="$PWD/../junk" install
); fi

# Build zip/unzip for Librewolf's sole use.
for f in zip unzip; do (
    cd "$f"

    make \
        CC="$CC $CFLAGS $CXXFLAGS" \
        -f unix/Makefile generic

    make \
        prefix="$PWD/../junk" \
        -f unix/Makefile install
); done

export PATH="$PWD/junk/bin:$PATH"

# Detect what the current linker is.
case "$(readlink "$(command -v ld)")" in
    ld.bfd) ld="bfd";;
    lld) ld="lld";;
    *) ld="other";;
esac

librewolf_patch_dir=common/patches/

patches="
remove_addons.patch
unity-menubar.patch
context-menu.patch
mozilla_dirs.patch
urlbarprovider-interventions.patch
allow-ubo-private-mode.patch
sed-patches/disable-pocket.patch
sed-patches/stop-undesired-requests.patch
ui-patches/remove-snippets-from-home.patch
ui-patches/sanitizing-description.patch
ui-patches/remove-organization-policy-banner.patch
ui-patches/pref-naming.patch
ui-patches/remove-branding-urlbar.patch
ui-patches/remove-cfrprefs.patch
"
for patch in $patches; do
    patch -Np1 < "${librewolf_patch_dir}$patch"
done

rm -f common/source_files/mozconfig
cp -r common/source_files/* .

sed "s/ccache_stats = None/return None/" \
    python/mozbuild/mozbuild/configure/check_debug_ranges.py > _
mv -f _ python/mozbuild/mozbuild/configure/check_debug_ranges.py

# If using libc++, CXXSTDLIB needs to be set manually.
case $("$CC" -print-file-name=libc++.so) in */*)
    export CXXSTDLIB=c++
    ;;
esac

# Instruct the compiler to trim absolute paths in resulting binaries and instead
# change them to relative paths ($PWD/... ./...).
export RUSTFLAGS="$RUSTFLAGS --remap-path-prefix=$PWD=."

export LDFLAGS="$LDFLAGS -Wl,-rpath=/usr/lib/librewolf,--enable-new-dtags"
export RUSTFLAGS="$RUSTFLAGS -Cdebuginfo=0"
export MACH_USE_SYSTEM_PYTHON=1
export MOZ_DEBUG_FLAGS=-g0
export MOZBUILD_STATE_PATH=$PWD/state
export MOZ_NOSPAM=1

cat > .mozconfig << EOF
ac_add_options --prefix=/usr
ac_add_options --libdir=/usr/lib
ac_add_options --enable-alsa
ac_add_options --enable-strip
ac_add_options --enable-release
ac_add_options --enable-rust-simd
ac_add_options --enable-install-strip
ac_add_options --enable-official-branding
ac_add_options --enable-application=browser
ac_add_options --enable-optimize="${CFLAGS:-} -w"
ac_add_options --with-system-libvpx
ac_add_options --with-system-ffi
ac_add_options --with-system-png
ac_add_options --with-system-jpeg
ac_add_options --with-system-zlib
ac_add_options --with-system-pixman
ac_add_options --without-system-nss
ac_add_options --without-system-nspr
ac_add_options --disable-eme
ac_add_options --disable-dbus
ac_add_options --enable-linker="$ld"
ac_add_options --disable-tests
ac_add_options --disable-vtune
ac_add_options --disable-updater
ac_add_options --disable-jemalloc
ac_add_options --disable-elf-hack
ac_add_options --disable-callgrind
ac_add_options --disable-profiling
ac_add_options --disable-necko-wifi
ac_add_options --disable-crashreporter
ac_add_options --disable-pulseaudio
ac_add_options --disable-accessibility
ac_add_options --disable-debug
ac_add_options --disable-debug-symbols
ac_add_options --disable-parental-controls
ac_add_options --disable-system-extension-dirs
ac_add_options --without-wasm-sandboxed-libraries

ac_add_options --with-app-name=librewolf
ac_add_options --with-app-basename=Librewolf
ac_add_options --with-branding=browser/branding/librewolf
ac_add_options --with-distribution-id=io.gitlab.librewolf-community
EOF

./mach build
./mach install

mkdir -p "$1/usr/lib/librewolf/"
cp -r settings/* "$1/usr/lib/librewolf/"

# Remove a lot of uneeded "stuff".
rm -rf \
    "$1/usr/include" \
    "$1/usr/lib/librewolf-devel" \
    "$1/usr/share/idl" \
    "$1/usr/lib/librewolf/browser/features/fxmonitor@mozilla.org.xpi" \
    "$1/usr/lib/librewolf/browser/features/screenshots@mozilla.org.xpi" \
    "$1/usr/lib/librewolf/browser/features/webcompat-reporter@mozilla.org.xpi" \
    "$1/usr/lib/librewolf/browser/features/webcompat@mozilla.org.xpi" \
    "$1/usr/lib/librewolf/browser/features/doh-rollout@mozilla.org.xpi"
