#!/bin/sh -e

# Remove compiler debug stuff and post-install message.
sed Makefile \
    -e '/CFLAGS.*-g/d' \
    -e '/^install:/s/ post-install$//' > _
mv -f _ Makefile

make
make PREFIX=/usr install
