#!/bin/sh -e

./configure \
    --prefix=/usr \
    --with-fontdir=/usr/share/fonts \
    --disable-xdmcp \
    --disable-xdm-auth-1

make
make DESTDIR="$1" install

chmod u+s "$1/usr/bin/Xfbdev"
chmod u+s "$1/usr/bin/Xvesa"

# Install minimum requirement for bitmap fonts.
mkdir -p "$1/usr/share/fonts/misc"
cp ./*.pcf.gz fonts.alias fonts.dir "$1/usr/share/fonts/misc"
