#!/bin/sh

./autogen.sh

./configure \
  --prefix=/usr \
  --with-fontdir=/usr/share/fonts


make
make install

chmod u+s "$1/usr/bin/Xfbdev"
chmod u+s "$1/usr/bin/Xvesa"

#install minimum requirement for bitmap fonts
mkdir -p "$1/usr/share/fonts/misc"
cp ./*.pcf.gz fonts.alias fonts.dir "$1/usr/share/fonts/misc"
