#!/bin/sh -e

export DESTDIR="$1"

patch -p1 < remove-malloc-stats.patch

muon setup \
    -Dprefix=/usr \
    -Dtee=enabled \
    -Dxcb=enabled \
    -Dxlib=enabled \
    -Dxlib-xcb=enabled \
    -Dtests=disabled \
    output

ninja -C output
muon  -C output install
