#!/bin/sh -e

export DESTDIR="$1"

meson setup \
    -Dprefix=/usr \
    -Dman=false \
    -Ddocbook_docs=disabled \
    -Dgtk_doc=false \
    -Dtests=false \
    -Dintrospection=disabled \
    output

ninja -C output
ninja -C output install
