#!/bin/sh -e

(   
    cd unix
    ./configure \
        --prefix=/usr \
        --mandir=/usr/share/man \
        --enable-64bit

    make
    make INSTALL_ROOT="$1" install install-private-headers
    ln -sf wish"${2%.*}"     "$1/usr/bin/wish"
    ln -sf libtk"${2%.*}".so "$1/usr/lib/libtk.so"
)

for dir in compat generic generic/ttk unix; do
    install -dm755   "$1/usr/include/tk-private/$dir"
    install -m644 -t "$1/usr/include/tk-private/$dir" "$dir"/*.h
done

# remove buildroot traces
sed -e "s#$PWD/unix#/usr/lib#" \
    -e "s#$PWD#/usr/include#" \
    "$1/usr/lib/tkConfig.sh" > _
mv -f _ "$1/usr/lib/tkConfig.sh"
