#!/bin/sh -e

export DESTDIR="$1"

# Make sure `gunzip` is available.
mkdir -p path
ln -s /usr/bin/pigz "$PWD/path/gunzip"
export PATH="$PWD/path:$PATH"

# Enable '-no-pie' as it can fix a seg fault in `temacs`.
export CFLAGS="$CFLAGS -no-pie"

kiss list libgccjit && conf="--with-native-compilation"

# Tree Sitter Check.
pkg-config --exists tree-sitter && conf="${conf:-} --with-tree-sitter"

autoreconf -vif

./configure \
    ${conf:-} \
    --prefix=/usr \
    --with-modules \
    --with-xft \
    --with-x-toolkit=athena \
    --without-toolkit-scroll-bars \
    --without-dbus \
    --without-gconf \
    --without-gsettings \
    --without-rsvg \
    --with-xpm=no \
    --with-tiff=no \
    --with-gnutls=yes

mkdir -p "$1/usr/share/emacs/site-lisp"
cat << EOF > "$1/usr/share/emacs/site-lisp/site-start.el"
;; Better security defaults
(with-eval-after-load 'gnutls
  (setq
   gnutls-verify-error t
   gnutls-min-prime-bits 2048
   gnutls-trustfiles '("/etc/ssl/cert.pem")))

;; Needed unless KISS Linux gains librsvg support
(setq-default shr-blocked-images ".*\.svg$")
EOF

# Disable ASLR for the build procedure, as it can lead to seg faults.
case "$(uname -m)" in
    x86_64) _arch=linux64 ;;
    i*86) _arch=linux32 ;;
esac
setarch $_arch -R make
make install

rm -rf "$1/usr/lib/systemd"
